##############################################
# Site wide configuration
##############################################
title: Kouei's Study
sub-title: Far a way to go
email: hkim3139@gmail.com 
description: >- # this means to ignore newlines until "baseurl:"
  A simple developer blog powered by jekyll.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8

##############################################
# Jekyll configuration
##############################################
timezone: Asia/Seoul
markdown: kramdown

##############################################
# Custom configuration
##############################################
profile-image: profile.png
profile-name: Hangyoung Kim
profile-comment: Backend Developer
